##############################################################################################
## HTTP requests for the administrator API                                                  ##
## all endpoints required an jwt token in the authorization header                          ##
## all endpoints can only be accessed by a user with the adminsitrator role                 ##
## a vscode extension called REST client by Hauchao Mao is required to send these requests  ##
## or you can use a standalone application like postman or insomnia :)                      ##
##############################################################################################

### this endpoints return an array of administrator objects ###
GET http://localhost:3000/api/users/administrators HTTP/1.1

### this endpoints return a administrator object specified by an id ###
GET http://localhost:3000/api/users/administrators/:id HTTP/1.1

### this endpoints creates & returns an administrator object ###
POST http://localhost:3000/api/users/administrators HTTP/1.1
Content-Type: application/json

{
    
}

### this endpoint updates and returns a administrator object ###
PUT http://localhost:3000/api/users/administrators/6379421fd37dfafafa4aa99c HTTP/1.1
Content-Type: application/json

{

}

### this endpoint deletes and returns a administrator object ###
DELETE http://localhost:3000/api/users/administrators/6379421fd37dfafafa4aa99c HTTP/1.1
